### ISSUE TITLE
validation.php not creating new order prestashop 1.6.1.1

### ISSUE THREAD

**Issue by husein522** [ashwch/Instamojo-PrestaShop#4]
validation.php not creating new order prestashop 1.6.1.1

**Comment by ashwch** [comment]
Please share the URL of the Payment link you're using with the plugin.

**Comment by husein522** [comment]
Hi ,

Below is the like I am using.

https://www.instamojo.com/huseinkolsawala/pay-now-9ec20/?embed=form&data_readonly=data_name&data_readonly=data_email&data_readonly=data_amount&data_readonly=data_phone&data_readonly=data_Field_94566&data_hidden=data_Field_94566&data_Field_94566=26-040200&data_name=Husein+kolsawala&data_email=husein.kolsawala%40spec-india.com&data_amount=20&data_phone=08983298153&data_sign=122a287b034fe7f26c2c3db925bbf7d293c0af11

validation.php is unable to create order from the cart.
Can you please check this

Thanks,
Husein

**Comment by ashwch** [comment]
You have not created the payment link properly.

1.  It should be payment link of type **"Services/Membership"**(that will remove the shipping and quantity  fields).
2. You have provided the redirection URL in the wrong field, i.e. Webhook. Paste it in **Custom Redirection URL* field in payment link's advanced settings.

**Comment by husein522** [comment]
Hi,
Thanks for reply,
I tried changing to Services/Membership and changed the redirection URL but still the issue exist :(

**Comment by ashwch** [comment]
Please share the URL of the new payment link you've created.

**Comment by husein522** [comment]
https://www.instamojo.com/huseinkolsawala/pay-with-instamojo-0f97b/?embed=form&data_readonly=data_name&data_readonly=data_email&data_readonly=data_amount&data_readonly=data_phone&data_readonly=data_Field_21579&data_hidden=data_Field_21579&data_Field_21579=26-083937&data_name=Husein+kolsawala&data_email=husein.kolsawala%40spec-india.com&data_amount=10&data_phone=08983298153&data_sign=ada4cd9980acbdabca6ea4d5673b11bd7df5112e

**Comment by ashwch** [comment]
I noticed that there's a redirection rule on your website. The URL you've provided as the custom redirection URL will always redirect to `http://burhanieshop.com/mystore/index.php`, hence it never hits the validation.php page.

**Comment by husein522** [comment]
The custom URL is set as  http://burhanieshop.com/mystore/modules/instmojo/validation.php
Can you help me why its not redirecting to above url

**Comment by ashwch** [comment]
It is working for me, are you making some changes right now?

**Comment by husein522** [comment]
Yes now it's working for me.
I had removed www. From the redirection URL

Thank you so much for your help
